# Generated by Django 3.2.9 on 2021-12-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commande_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='zipcode',
        ),
    ]
